/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aman
 */
public class Admin_Student_Add extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Student_Add
     */
    public Admin_Student_Add() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        fnt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lnt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        unt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        emailt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        pass1t = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        pass2t = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        f_patht = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        class2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/back_arrow.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/user.png"))); // NOI18N
        jLabel9.setText("Add New Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(727, 727, 727)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(250, 250, 250));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("First Name :");

        fnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        fnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        lnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        unt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        unt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        emailt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emailt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        pass1t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass1t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass1t.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        pass2t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass2t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass2t.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        f_patht.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        f_patht.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f_patht.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        f_patht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_pathtActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Last Name :");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("User Name/Display Name :");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("E-Mail ID :");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Password :");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password :");

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Folder Path :");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remove Student");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setText("...");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Class");

        class2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        class2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)
                        .addGap(85, 85, 85)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(class2)
                            .addComponent(jSeparator7)
                            .addComponent(f_patht, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(jSeparator6)
                            .addComponent(pass2t)
                            .addComponent(jSeparator5)
                            .addComponent(pass1t)
                            .addComponent(jSeparator4)
                            .addComponent(emailt)
                            .addComponent(jSeparator3)
                            .addComponent(unt)
                            .addComponent(fnt)
                            .addComponent(lnt)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fnt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass1t, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass2t, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_patht, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Admin_Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked
    String fn,ln,un,email,pass1,pass2,f_path,class1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         fn=fnt.getText().trim().toLowerCase();
        ln=lnt.getText().trim().toLowerCase();
        un=unt.getText().trim().toLowerCase();
        pass1=new String(pass1t.getPassword()).trim();
        pass2=new String(pass2t.getPassword()).trim();
        email=emailt.getText().trim().toLowerCase();
        f_path=f_patht.getText().trim();
        class1=class2.getText().trim();
        
        
        
        String regex1 = "^[a-zA-Z]+$";
        String regex2 = "^[a-zA-Z0-9]+$";
        
        try
        {
                //null check
            if(fn.equals("") || ln.equals("") || un.equals("") || pass1.equals("") || pass2.equals("") || email.equals("") || f_path.equals("") || class1.equals("") )
            {
                
                jTextArea1.append("\nAny field cannot be null");
            }
            else        //fields validations
            {
                if (fn.matches(regex1) && ln.matches(regex1)) {  //fn ln condtion check
                    if(un.matches(regex2))      //un condtion check
                    {
                        //boolean c=true;
                        String c=this.checkUN(un);
                        
                        if("false".equals(c))
                        {
                            jTextArea1.append("\nUserName is already Taken");
                        }
                        else if("error".equals(c))
                            jTextArea1.append("\nError occurred");
                        else if("true".equals(c))
                        {
                            if(pass1.equals(pass2))                //Final password & Email Check
                            {
                               
                                try{
                                    InternetAddress in=new InternetAddress(email);
                                    in.validate();
                                   
                                    String e=this.checkEmail(email);
                        
                                    if("false".equals(e))
                                    {
                                        jTextArea1.append("\nEmail is already Taken");
                                    }
                                    else if("error".equals(e))
                                        jTextArea1.append( "\nError occurred");
                                    
                                    else if("true".equals(e))
                                    {
                                        boolean s=this.storeData(fn, ln, un, pass1, email, f_path,class1);
                                        if(s==true)                                                        //Final Check
                                        {
                                            Thread t1=new Thread(()->{new SendEmail().registerUserConfirmation(email, un, fn, ln, pass1);});
                                            Thread t2=new Thread(()->{jTextArea1.setText("User "+fn+" "+ln+" added successfully"); });
                                            
                                            t1.start();
                                            t2.start();
                                            
                                        }
                                        else
                                           jTextArea1.append("\nData did not get registered");
                                        }
                                }
                                catch(AddressException ae)
                                {
                                    jTextArea1.append("\nEmail not valid");
                                }
                            }
                            else
                            {
                                jTextArea1.append( "\nPassword doesn't match");
                                pass1t.setText("");
                                pass2t.setText("");
                            }
                        }
                    }
                    else
                    {
                        jTextArea1.append("\nUser name can only take alphabets and numbers");
                        lnt.setText("");
                        pass1t.setText("");
                        pass2t.setText("");
                    }
                }
                else                                    //fn ln condtion check
                {
                    jTextArea1.append("\nFirst name and Last name should only consist alphabets");
                    fnt.setText("");
                    lnt.setText("");
                    pass1t.setText("");
                    pass2t.setText("");
                }
            }
             }
            catch(Exception e)
            {
                    jTextArea1.append( "\nSomething went wrong");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser jc=new JFileChooser("D:");
         jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         //jc.setBackground(Color.red);
         
         jc.showDialog(null,"Select folder");
         //System.out.print(jc.getSelectedFile().toString());
         
         f_patht.setText(jc.getSelectedFile().toString().trim());
         //else
           //  jtf.setText("");
        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fnt.setText("");
        lnt.setText("");
        unt.setText("");
        emailt.setText("");
        f_patht.setText("");
        pass1t.setText("");
        pass2t.setText("");
        jTextArea1.setText("");
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
        
          fn=fnt.getText().trim().toLowerCase();
        ln=lnt.getText().trim().toLowerCase();
        un=unt.getText().trim().toLowerCase();
        pass1=new String(pass1t.getPassword()).trim();
        pass2=new String(pass2t.getPassword()).trim();
        email=emailt.getText().trim().toLowerCase();
        f_path=f_patht.getText().trim();
        class1=class2.getText().trim();
        
        
        
        String regex1 = "^[a-zA-Z]+$";
        String regex2 = "^[a-zA-Z0-9]+$";
        
        try
        {
                //null check
            if(fn.equals("") || ln.equals("") || un.equals("") || pass1.equals("") || pass2.equals("") || email.equals("") || f_path.equals("") || class1.equals("") )
            {
                
                jTextArea1.append("\nAny field cannot be null");
            }
            else        //fields validations
            {
                if (fn.matches(regex1) && ln.matches(regex1)) {  //fn ln condtion check
                    if(un.matches(regex2))      //un condtion check
                    {
                        //boolean c=true;
                        String c=this.checkUN(un);
                        
                        if("false".equals(c))
                        {
                            jTextArea1.append("\nUserName is already Taken");
                        }
                        else if("error".equals(c))
                            jTextArea1.append("\nError occurred");
                        else if("true".equals(c))
                        {
                            if(pass1.equals(pass2))                //Final password & Email Check
                            {
                               
                                try{
                                    InternetAddress in=new InternetAddress(email);
                                    in.validate();
                                   
                                    String e=this.checkEmail(email);
                        
                                    if("false".equals(e))
                                    {
                                        jTextArea1.append("\nEmail is already Taken");
                                    }
                                    else if("error".equals(e))
                                        jTextArea1.append( "\nError occurred");
                                    
                                    else if("true".equals(e))
                                    {
                                        boolean s=this.storeData(fn, ln, un, pass1, email, f_path,class1);
                                        if(s==true)                                                        //Final Check
                                        {
                                            Thread t1=new Thread(()->{new SendEmail().registerUserConfirmation(email, un, fn, ln, pass1);});
                                            Thread t2=new Thread(()->{jTextArea1.setText("User "+fn+" "+ln+" added successfully"); });
                                            
                                            t1.start();
                                            t2.start();
                                            
                                        }
                                        else
                                           jTextArea1.append("\nData did not get registered");
                                        }
                                }
                                catch(AddressException ae)
                                {
                                    jTextArea1.append("\nEmail not valid");
                                }
                            }
                            else
                            {
                                jTextArea1.append( "\nPassword doesn't match");
                                pass1t.setText("");
                                pass2t.setText("");
                            }
                        }
                    }
                    else
                    {
                        jTextArea1.append("\nUser name can only take alphabets and numbers");
                        lnt.setText("");
                        pass1t.setText("");
                        pass2t.setText("");
                    }
                }
                else                                    //fn ln condtion check
                {
                    jTextArea1.append("\nFirst name and Last name should only consist alphabets");
                    fnt.setText("");
                    lnt.setText("");
                    pass1t.setText("");
                    pass2t.setText("");
                }
            }
             }
            catch(Exception e)
            {
                    jTextArea1.append( "\nSomething went wrong");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
         
        Admin_Remove_Student cls2 = new Admin_Remove_Student();
        cls2.setVisible(true);
        cls2.pack();
        cls2.setLocationRelativeTo(null);
        cls2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void f_pathtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_pathtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_pathtActionPerformed

    private void class2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class2ActionPerformed
        
        
        
    public boolean storeData(String fn, String ln, String un, String pass1, String email, String f_path,String class1) 
    {
        String epass=encryptPass.encrypt(pass1);
        try(Connection con=DBUtil.getConnection())
        {
            PreparedStatement pr=con.prepareStatement("INSERT into user values (null,?,?,?,?,?,?,?)");
            
            pr.setString(1,fn);
            pr.setString(2,ln);
            pr.setString(3,un);
            pr.setString(4,email);
            pr.setString(5,epass);
            pr.setString(6,f_path);
            
            pr.setString(7,class1);
            pr.execute();
            
            return true;
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e);
            return false;
        }

    }
    public String checkUN(String uns)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            PreparedStatement pr=con.prepareStatement("SELECT fname from user WHERE uname='"+uns+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    public String checkEmail(String email)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            System.out.println(con.getCatalog());
            PreparedStatement pr=con.prepareStatement("SELECT fname from user WHERE email='"+email+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
        
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Student_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField class2;
    private javax.swing.JTextField emailt;
    private javax.swing.JTextField f_patht;
    private javax.swing.JTextField fnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lnt;
    private javax.swing.JPasswordField pass1t;
    private javax.swing.JPasswordField pass2t;
    private javax.swing.JTextField unt;
    // End of variables declaration//GEN-END:variables
}
