/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aman
 */
public class Admin_Teacher_Add extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Teacher_Add
     */
    public Admin_Teacher_Add() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);
        this.setResizable(false);
        pass1t.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lnt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        emailt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        pass1t = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        f_patht = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        unt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pass2t = new javax.swing.JPasswordField();
        chkFYFS = new javax.swing.JCheckBox();
        chkSYFS = new javax.swing.JCheckBox();
        chkTYFS = new javax.swing.JCheckBox();
        chkFYSS = new javax.swing.JCheckBox();
        chkSYSS = new javax.swing.JCheckBox();
        chkTYSS = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/back_arrow.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/teacher.png"))); // NOI18N
        jLabel8.setText("Add New Teacher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("First Name :");

        fnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        fnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Last Name :");

        lnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lnt.setOpaque(false);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("E-Mail ID :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        emailt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emailt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Password :");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        pass1t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass1t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass1t.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Folder Path:");

        f_patht.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        f_patht.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f_patht.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("User Name/Display Name :");

        unt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        unt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(238, 234, 234));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("...");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Teacher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(250, 250, 250));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Confirm Password :");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        pass2t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass2t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass2t.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        chkFYFS.setText("FYFS");
        chkFYFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFYFSActionPerformed(evt);
            }
        });

        chkSYFS.setText("SYFS");
        chkSYFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSYFSActionPerformed(evt);
            }
        });

        chkTYFS.setText("TYFS");

        chkFYSS.setText("FYSS");

        chkSYSS.setText("SYSS");

        chkTYSS.setText("TYSS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Choose class");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Remove Teacher");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator3)
                                            .addComponent(jSeparator4)
                                            .addComponent(jSeparator2)
                                            .addComponent(jSeparator1)
                                            .addComponent(fnt, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                            .addComponent(emailt)
                                            .addComponent(pass1t)
                                            .addComponent(lnt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(unt)
                                            .addComponent(pass2t)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator7)))))
                        .addContainerGap(366, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(f_patht)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(chkFYSS)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(chkSYSS))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(chkFYFS)
                                                .addGap(85, 85, 85)
                                                .addComponent(chkSYFS)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkTYFS, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chkTYSS, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(304, 304, 304))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass1t, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass2t, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f_patht, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFYFS)
                    .addComponent(chkSYFS)
                    .addComponent(chkTYFS))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkFYSS)
                            .addComponent(chkSYSS)
                            .addComponent(chkTYSS)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10)))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Admin_Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    String fn,ln,un,email,pass1,pass2,f_path, chkFYFS1,chkSYFS1,chkTYFS1,chkFYSS1, chkSYSS1,chkTYSS1;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        fn=fnt.getText().trim().toLowerCase();
        ln=lnt.getText().trim().toLowerCase();
        un=unt.getText().trim().toLowerCase();
        pass1=new String(pass1t.getPassword()).trim();
        pass2=new String(pass2t.getPassword()).trim();
        email=emailt.getText().trim().toLowerCase();
        f_path=f_patht.getText().trim();
        chkFYFS1=chkFYFS.getText().trim();
        chkSYFS1=chkSYFS.getText().trim();
        chkTYFS1=chkTYFS.getText().trim();
        chkFYSS1=chkFYSS.getText().trim();
        chkSYSS1=chkSYSS.getText().trim();
        chkTYSS1=chkTYSS.getText().trim();
        
        
        String regex1 = "^[a-zA-Z]+$";
        String regex2 = "^[a-zA-Z0-9]+$";
        
        
        if(chkFYFS.isSelected()){
          chkFYFS1="yes";  
        }
        
        
        if(chkSYFS.isSelected()){
          chkSYFS1="yes";  
        }
        
        if(chkTYFS.isSelected()){
          chkTYFS1="yes";  
        }
        
        if(chkFYSS.isSelected()){
          chkFYSS1="yes";  
        }
        
        if(chkSYSS.isSelected()){
          chkSYSS1="yes";  
        }
        
        if(chkTYSS.isSelected()){
          chkTYSS1="yes";  
        }
        
        try
        {
                //null check
            if(fn.equals("") || ln.equals("") || un.equals("") || pass1.equals("") || pass2.equals("") || email.equals("") || f_path.equals("") )
            {
                JOptionPane.showMessageDialog(null, "Any field cannot be null");
            }
            else        //fields validations
            {
                if (fn.matches(regex1) && ln.matches(regex1)) {  //fn ln condtion check
                    if(un.matches(regex2))      //un condtion check
                    {
                        //boolean c=true;
                        String c=this.checkUN(un);
                        
                        if("false".equals(c))
                        {
                            JOptionPane.showMessageDialog(null, "UserName is already Taken");
                        }
                        else if("error".equals(c))
                            JOptionPane.showMessageDialog(null, "Error occurred");
                        else if("true".equals(c))
                        {
                            if(pass1.equals(pass2))                //Final password & Email Check
                            {
                               
                                try{
                                    InternetAddress in=new InternetAddress(email);
                                    in.validate();
                                   
                                    String e=this.checkEmail(email);
                        
                                    if("false".equals(e))
                                    {
                                        JOptionPane.showMessageDialog(null, "Email is already Taken");
                                    }
                                    else if("error".equals(e))
                                        JOptionPane.showMessageDialog(null, "Error occurred");
                                    
                                    else if("true".equals(e))
                                    {
                                        boolean s=this.storeData(fn, ln, un, pass1, email, f_path, chkFYFS1,chkSYFS1,chkTYFS1,chkFYSS1, chkSYSS1,chkTYSS1);
                                        if(s==true)                                                        //Final Check
                                        {
                                            Thread t1=new Thread(()->{new SendEmail().registerTeacherConfirmation(email, un, fn, ln, pass1);});
                                            Thread t2=new Thread(()->{jTextArea1.setText("Teacher "+fn+" "+ln+" added successfully"); });
                                            
                                            t1.start();
                                            t2.start();
                                            
                                          
                                        }
                                        else
                                           JOptionPane.showMessageDialog(null, "Data did not get registered");
                                        }
                                }
                                catch(AddressException ae)
                                {
                                    JOptionPane.showMessageDialog(null, "Email not valid");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Password doesn't match");
                                pass1t.setText("");
                                pass2t.setText("");
                            }
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "User name can only take alphabets and numbers");
                        unt.setText("");
                        pass1t.setText("");
                        pass2t.setText("");
                    }
                }
                else                                    //fn ln condtion check
                {
                    JOptionPane.showMessageDialog(null, "First name and Last name should only consist alohabets");
                    fnt.setText("");
                    lnt.setText("");
                    pass1t.setText("");
                    pass2t.setText("");
                }
            }
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null, "Something went wrong");
        }   
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser jc=new JFileChooser("D:");
         jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         //jc.setBackground(Color.red);
         
         jc.showDialog(null,"Select folder");
         //System.out.print(jc.getSelectedFile().toString());
         
         f_patht.setText(jc.getSelectedFile().toString().trim());
         //else
           //  jtf.setText("");
        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        fnt.setText("");
        lnt.setText("");
        unt.setText("");
        emailt.setText("");
        f_patht.setText("");
        pass1t.setText("");
        pass2t.setText("");
        chkFYFS.setSelected(false);
        chkSYFS.setSelected(false);
        chkTYFS.setSelected(false);
        chkFYSS.setSelected(false);
        chkSYSS.setSelected(false);
        chkTYSS.setSelected(false);
        
        jTextArea1.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chkFYFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFYFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFYFSActionPerformed

    private void chkSYFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSYFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSYFSActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        
         
        Admin_Remove_Teacher cls3 = new Admin_Remove_Teacher();
        cls3.setVisible(true);
        cls3.pack();
        cls3.setLocationRelativeTo(null);
        cls3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton4MouseClicked

    
    public boolean storeData(String fn, String ln, String un, String pass1, String email, String f_path,String chkFYFS1, String chkSYFS1,String chkTYFS1,String chkFYSS1, String chkSYSS1,String chkTYSS1) 
    {
        String epass=encryptPass.encrypt(pass1);
        try
        {   
            Connection con=DBUtil.getConnection();
            PreparedStatement pr=con.prepareStatement("INSERT into teacher values (null,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            pr.setString(1,fn);
            pr.setString(2,ln);
            pr.setString(3,un);
            pr.setString(4,email);
            pr.setString(5,epass);
            pr.setString(6,f_path);
            pr.setString(7,chkFYFS1);
            pr.setString(8,chkSYFS1);
            pr.setString(9,chkTYFS1);
            pr.setString(10,chkFYSS1);
            pr.setString(11,chkSYSS1);
            pr.setString(12,chkTYSS1);
            
            
            pr.execute();
            
            return true;
        }
        catch(SQLException e)
        {
            return false;
        }

    }
    public String checkUN(String uns)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            PreparedStatement pr=con.prepareStatement("SELECT fname from teacher WHERE tname='"+uns+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    public String checkEmail(String email)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            PreparedStatement pr=con.prepareStatement("SELECT fname from teacher WHERE email='"+email+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Teacher_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Teacher_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Teacher_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Teacher_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Teacher_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFYFS;
    private javax.swing.JCheckBox chkFYSS;
    private javax.swing.JCheckBox chkSYFS;
    private javax.swing.JCheckBox chkSYSS;
    private javax.swing.JCheckBox chkTYFS;
    private javax.swing.JCheckBox chkTYSS;
    private javax.swing.JTextField emailt;
    private javax.swing.JTextField f_patht;
    private javax.swing.JTextField fnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lnt;
    private javax.swing.JPasswordField pass1t;
    private javax.swing.JPasswordField pass2t;
    private javax.swing.JTextField unt;
    // End of variables declaration//GEN-END:variables
}
