/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aman
 */
public class Profile extends javax.swing.JFrame {

    private String type;
    private int uid;
    private String uun,ufn,uln, uemail;

    /**
     * Creates new form Profile
     * @param type
     * @param uid
     */
    public Profile()
    {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.setLocationRelativeTo(null);
        this.setTitle("Profile");
        this.getContentPane().setBackground(Color.BLACK);
        this.setResizable(false);
        
        utt.setEnabled(false);
        uidt.setEnabled(false);
        unt.setEnabled(false);
        fnt.setEnabled(false);
        lnt.setEnabled(false);
        emailt.setEnabled(false);
     
    }
    
    public Profile(String type,int uid) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.setLocationRelativeTo(null);
        this.setTitle("Profile");
        this.getContentPane().setBackground(Color.BLACK);
        this.setResizable(false);
        
        utt.setEnabled(false);
        uidt.setEnabled(false);
        unt.setEnabled(false);
        fnt.setEnabled(false);
        lnt.setEnabled(false);
        emailt.setEnabled(false);
        
        this.type = type;
        this.uid = uid;
        
        this.getAllUserData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        utt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        uidt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        unt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fnt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lnt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        emailt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User Name :");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("First Name :");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Last Name :");
        jLabel4.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("User Type :");
        jLabel5.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("E-Mail :");
        jLabel6.setToolTipText("");

        utt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        uidt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        uidt.setToolTipText("");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        unt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        fnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        lnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        emailt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uidt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(utt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(uidt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(unt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(emailt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6)
                .addGap(195, 195, 195))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn1.setText("Enable Editing");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn3.setText("Change Password");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn2.setText("Save Changes");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn4.setText("Refresh");
        btn4.setBorderPainted(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator7)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn1)
                .addGap(67, 67, 67)
                .addComponent(btn2)
                .addGap(69, 69, 69)
                .addComponent(btn4)
                .addGap(73, 73, 73)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn3)
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if((btn1.getText()).equals("Enable Editing"))
        {
            unt.setEnabled(true);
            fnt.setEnabled(true);
            lnt.setEnabled(true);
            emailt.setEnabled(true);
            btn2.setEnabled(true);
            btn1.setText("Disable Editing");
        }
        else if((btn1.getText()).equals("Disable Editing"))
        {
            unt.setEnabled(false);
            fnt.setEnabled(false);
            lnt.setEnabled(false);
            emailt.setEnabled(false);
            btn2.setEnabled(false);
            btn1.setText("Enable Editing");
        }
        
    }//GEN-LAST:event_btn1ActionPerformed
    String fn,ln,un,email;
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        fn=fnt.getText().trim().toLowerCase();
        ln=lnt.getText().trim().toLowerCase();
        un=unt.getText().trim().toLowerCase();
        email=emailt.getText().trim().toLowerCase();
        
        
        String regex1 = "^[a-zA-Z]+$";
        String regex2 = "^[a-zA-Z0-9]+$";
        
        try
        {
                //null check
            if(fn.equals("") || ln.equals("") || un.equals("") || email.equals("") )
            {
                
                JOptionPane.showMessageDialog(null,"Any field cannot be null");
            }
            else        //fields validations
            {
                if (fn.matches(regex1) && ln.matches(regex1)) {  //fn ln condtion check
                    if(un.matches(regex2))      //un condtion check
                    {
                        //boolean c=true;
                        String c=this.checkUN(un);
                        
                        if("false".equals(c) && !uun.equals(un))
                        {
                            JOptionPane.showMessageDialog(null,"UserName is already Taken");
                        }
                        else if("error".equals(c))
                            JOptionPane.showMessageDialog(null,"Error occurred");
                        else if("true".equals(c) || uun.equals(un))
                        {
                            
                                try{
                                    InternetAddress in=new InternetAddress(email);
                                    in.validate();
                                   
                                    String e=this.checkEmail(email);
                        
                                    if("false".equals(e) && !uemail.equals(email))
                                    {
                                        JOptionPane.showMessageDialog(null,"Email is already Taken");
                                    }
                                    else if("error".equals(e))
                                        JOptionPane.showMessageDialog(null,"Error occurred");
                                    
                                    else if("true".equals(e) || uemail.equals(email))
                                    {
                                        boolean s=this.storeData(fn, ln, un, email);
                                        if(s==true)                                                        //Final Check
                                        {
                                            Thread t1=new Thread(()->{new SendEmail().updateSuccessful(fn, ln, un, email, type);});
                                            Thread t2=new Thread(()->{JOptionPane.showMessageDialog(null,"User details updated successfully"); });
                                            btn2.setEnabled(false);
                                            t1.start();
                                            t2.start();
                                            
                                        }
                                        else
                                           JOptionPane.showMessageDialog(null,"Data did not get registered");
                                        }
                                }
                                catch(AddressException ae)
                                {
                                    JOptionPane.showMessageDialog(null,"Email not valid");
                                }
                            
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"User name can only take alphabets and numbers");
                        lnt.setText("");
                        
                    }
                }
                else                                    //fn ln condtion check
                {
                    JOptionPane.showMessageDialog(null,"First name and Last name should only consist alphabets");
                    fnt.setText("");
                    lnt.setText("");
                }
            }
             }
            catch(Exception e)
            {
                    JOptionPane.showMessageDialog(null, "Something went wrong");
            }
        
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        this.getAllUserData();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Thread t1=new Thread(()->{new forget_password_step2(uemail,type,1).setVisible(true);});
        Thread t2=new Thread(()->{new SendEmail().sendOTPEmail(uemail);});
        t1.start();
        t2.start();
    }//GEN-LAST:event_btn3ActionPerformed

    
    public boolean storeData(String fn, String ln, String un, String email) 
    {
        PreparedStatement pr=null;
        try
        {
            Connection con=DBUtil.getConnection();
            if(type.equals("s"))
                pr=con.prepareStatement("update user set fname='"+fn+"', lname='"+ln+"', uname='"+un+"' , email='"+email+"' where uid="+uid+"");
            if(type.equals("t"))
                pr=con.prepareStatement("update teacher set fname='"+fn+"', lname='"+ln+"', tname='"+un+"' , email='"+email+"' where tid="+uid+"");
            
            pr.execute();
            
            return true;
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e);
            return false;
        }

    }
    public String checkUN(String uns)  
    {
        ResultSet rs=null;
        
        try
        {
            PreparedStatement pr=null;
            Connection con1=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            if(type.equals("s"))
                pr=con1.prepareStatement("SELECT fname from user WHERE uname='"+uns+"'");
            if(type.equals("t"))
                pr=con1.prepareStatement("SELECT fname from teacher WHERE tname='"+uns+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)   //if this condition is true then username doesnt exit itll return true
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false"; //username exits return false
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    public String checkEmail(String email)  
    {
        ResultSet rs=null;
        
        try
        {
            PreparedStatement pr=null;
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            if(type.equals("s"))
                pr=con.prepareStatement("SELECT fname from user WHERE email='"+email+"'");
            if(type.equals("t"))
                pr=con.prepareStatement("SELECT fname from teacher WHERE email='"+email+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";     //email doesnt exists send true
            }
            return "false";  //email exists send false
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    
    private void getAllUserData() 
    {
        try
        {
            Connection con=DBUtil.getConnection();
            PreparedStatement pr=null;
            
            if(type.equals("s"))
                pr=con.prepareStatement("select fname,lname,uname,email from user where uid="+uid+"");
            if(type.equals("t"))
                pr=con.prepareStatement("select fname,lname,tname,email from teacher where tid="+uid+"");
            
            ResultSet rs=pr.executeQuery();
            while(rs.next())
            {
                ufn=rs.getString(1);
                uln=rs.getString(2);
                uun=rs.getString(3);
                uemail=rs.getString(4);
            }
            if(type.equals("s"))
                utt.setText("Student");
            if(type.equals("t"))
                utt.setText("Teacher");
            uidt.setText(uid+"");
            fnt.setText(ufn);
            lnt.setText(uln);
            unt.setText(uun);
            emailt.setText(uemail);
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println("getAllData \n\n "+e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JTextField emailt;
    private javax.swing.JTextField fnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lnt;
    private javax.swing.JTextField uidt;
    private javax.swing.JTextField unt;
    private javax.swing.JTextField utt;
    // End of variables declaration//GEN-END:variables

    
}
