/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Aman
 */
public class Teacher_Student_Class_Show extends javax.swing.JFrame {

    /**
     * Creates new form showclass
     */
int tid;
    public Teacher_Student_Class_Show() {
        initComponents();
              
                
        
        
    }

    Teacher_Student_Class_Show(int tid) {
      
         initComponents();
        this.tid=tid;
        System.out.println(tid);//To change body of generated methods, choose Tools | Templates.
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton1.setText("FYFS");
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jButton1ComponentMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "fname", "lname", "uname", "email", "password", "folder_path", "class1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("FYFS");
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jButton2ComponentMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("FYSS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SYFS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SYSS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("TYFS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("TYSS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ComponentMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkFYFS from teacher where TID= "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkFYFS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='FYFS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ComponentMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkFYFS from teacher where TID= "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkFYFS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='FYFS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkFYSS from teacher where TID= "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkFYSS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='FYSS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String updateQuery="select chkSYFS from teacher where TID = "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkSYFS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='SYFS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }

        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkSYSS from teacher where TID="+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkSYSS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='SYSS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkTYFS from teacher where TID= "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkTYFS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='TYFS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String updateQuery="select chkFYSS from teacher where TID= "+tid+"";

        try
        {
            Connection con=DBUtil.getConnection();

            PreparedStatement pr=con.prepareStatement(updateQuery);

            ResultSet rs=pr.executeQuery();

            while(rs.next())
            {
                String class2 = rs.getString("chkFYSS");

                System.out.println(class2);

                if("yes".equals(class2))
                {
                    try
                    {
                        String updateQuery1="select fname,lname,uname,email,password from user where class1='FYSS'";

                        Connection con1=DBUtil.getConnection();

                        PreparedStatement pro=con1.prepareStatement(updateQuery1);

                        ResultSet rs1;
                        rs1 = pro.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));

                    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(null,e);

                    }

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You are not authorise Person");

                }

            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton8ActionPerformed
String un1;
int id;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Student_Class_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Student_Class_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Student_Class_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Student_Class_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Teacher_Student_Class_Show().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
