/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.internet.AddressException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.mail.internet.InternetAddress;
/**
 *
 * @author Aman
 */
public class User_Register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public User_Register() {
        initComponents();
        
        left_panel.setBackground(new Color(0,0,0,100));
   //    right_panel.setBackground(new Color(0,0,0,100));

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        right_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lnt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        unt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        pass1t = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        pass2t = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        emailt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        f_patht = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cla1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        left_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        right_panel.setBackground(new java.awt.Color(32, 33, 35));
        right_panel.setForeground(new java.awt.Color(255, 255, 255));
        right_panel.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/register.png"))); // NOI18N
        right_panel.add(jLabel2);
        jLabel2.setBounds(38, 13, 32, 32);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        right_panel.add(jLabel3);
        jLabel3.setBounds(38, 52, 130, 22);

        fnt.setBackground(new java.awt.Color(32, 33, 35));
        fnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        fnt.setForeground(new java.awt.Color(255, 255, 255));
        fnt.setBorder(null);
        right_panel.add(fnt);
        fnt.setBounds(38, 81, 362, 22);
        right_panel.add(jSeparator1);
        jSeparator1.setBounds(38, 110, 362, 10);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        right_panel.add(jLabel4);
        jLabel4.setBounds(38, 133, 130, 22);

        lnt.setBackground(new java.awt.Color(32, 33, 35));
        lnt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lnt.setForeground(new java.awt.Color(255, 255, 255));
        lnt.setBorder(null);
        right_panel.add(lnt);
        lnt.setBounds(38, 162, 362, 22);
        right_panel.add(jSeparator2);
        jSeparator2.setBounds(38, 191, 362, 10);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User name");
        right_panel.add(jLabel5);
        jLabel5.setBounds(38, 208, 130, 22);

        unt.setBackground(new java.awt.Color(32, 33, 35));
        unt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        unt.setForeground(new java.awt.Color(255, 255, 255));
        unt.setBorder(null);
        right_panel.add(unt);
        unt.setBounds(38, 237, 362, 22);
        right_panel.add(jSeparator3);
        jSeparator3.setBounds(38, 266, 362, 10);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        right_panel.add(jLabel6);
        jLabel6.setBounds(38, 283, 130, 22);

        pass1t.setBackground(new java.awt.Color(32, 33, 35));
        pass1t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass1t.setForeground(new java.awt.Color(255, 255, 255));
        pass1t.setBorder(null);
        right_panel.add(pass1t);
        pass1t.setBounds(38, 312, 362, 22);
        right_panel.add(jSeparator4);
        jSeparator4.setBounds(38, 341, 362, 10);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");
        right_panel.add(jLabel8);
        jLabel8.setBounds(38, 358, 362, 22);

        pass2t.setBackground(new java.awt.Color(32, 33, 35));
        pass2t.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pass2t.setForeground(new java.awt.Color(255, 255, 255));
        pass2t.setBorder(null);
        right_panel.add(pass2t);
        pass2t.setBounds(38, 387, 362, 22);
        right_panel.add(jSeparator5);
        jSeparator5.setBounds(38, 416, 362, 10);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        right_panel.add(jLabel7);
        jLabel7.setBounds(38, 433, 130, 22);

        emailt.setBackground(new java.awt.Color(32, 33, 35));
        emailt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emailt.setForeground(new java.awt.Color(255, 255, 255));
        emailt.setBorder(null);
        right_panel.add(emailt);
        emailt.setBounds(38, 462, 362, 22);
        right_panel.add(jSeparator6);
        jSeparator6.setBounds(38, 491, 362, 10);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/register1.png"))); // NOI18N
        jLabel9.setText("Register");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        right_panel.add(jPanel1);
        jPanel1.setBounds(38, 661, 143, 35);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/close.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        right_panel.add(jLabel10);
        jLabel10.setBounds(586, 0, 32, 45);

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/user.png"))); // NOI18N
        jLabel11.setText("Already a user? Click to login");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        right_panel.add(jLabel11);
        jLabel11.setBounds(330, 664, 278, 32);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Folder-Path");
        right_panel.add(jLabel13);
        jLabel13.setBounds(38, 512, 114, 22);

        f_patht.setBackground(new java.awt.Color(32, 33, 35));
        f_patht.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        f_patht.setForeground(new java.awt.Color(255, 255, 255));
        f_patht.setToolTipText("");
        f_patht.setBorder(null);
        right_panel.add(f_patht);
        f_patht.setBounds(38, 546, 362, 22);
        right_panel.add(jSeparator7);
        jSeparator7.setBounds(40, 650, 362, 10);

        jButton1.setBackground(new java.awt.Color(30, 30, 30));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        right_panel.add(jButton1);
        jButton1.setBounds(219, 508, 31, 31);

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Class");
        right_panel.add(jLabel14);
        jLabel14.setBounds(38, 592, 130, 22);

        cla1.setBackground(new java.awt.Color(32, 33, 35));
        cla1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        cla1.setForeground(new java.awt.Color(255, 255, 255));
        cla1.setBorder(null);
        right_panel.add(cla1);
        cla1.setBounds(38, 621, 370, 22);
        right_panel.add(jSeparator8);
        jSeparator8.setBounds(38, 575, 362, 10);

        getContentPane().add(right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 630, 730));

        left_panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(130, 130, 130))
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel12)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        getContentPane().add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/laptop-desk.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x1,y1;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
          this.setOpacity((float)0.4);
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-x1, y-y1);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
          x1=evt.getX();
        y1=evt.getY();
      
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
          this.setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel11.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new User_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser jc=new JFileChooser("D:");
         jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         //jc.setBackground(Color.red);
         
         jc.showDialog(null,"Select folder");
         //System.out.print(jc.getSelectedFile().toString());
         
         f_patht.setText(jc.getSelectedFile().getAbsolutePath().toString().trim());
         String path1=jc.getSelectedFile().toString().trim();
         
        // String path2=jc.getSelectedFile().toString().trim().replaceAll("\\","\\\\");
         //System.out.print(path1+"\n"+path2);

            //else
           //  jtf.setText("");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    String fn,ln,un,pass1,pass2,email,f_path,cla;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        //fetching all data 
        fn=fnt.getText().trim().toLowerCase();
        ln=lnt.getText().trim().toLowerCase();
        un=unt.getText().trim().toLowerCase();
        pass1=new String(pass1t.getPassword()).trim();
        pass2=new String(pass2t.getPassword()).trim();
        email=emailt.getText().trim().toLowerCase();
        f_path=f_patht.getText().trim();
        cla=cla1.getText().trim();
        
        
        String regex1 = "^[a-zA-Z]+$";
        String regex2 = "^[a-zA-Z0-9]+$";
        
        try
        {
                //null check
            if(fn.equals("") || ln.equals("") || un.equals("") || pass1.equals("") || pass2.equals("") || email.equals("") || f_path.equals("") || cla.equals("") )
            {
                JOptionPane.showMessageDialog(null, "Any field cannot be null");
            }
            else        //fields validations
            {
                if (fn.matches(regex1) && ln.matches(regex1)) {  //fn ln condtion check
                    if(un.matches(regex2))      //un condtion check
                    {
                        //boolean c=true;
                        String c=this.checkUN(un);
                        
                        if("false".equals(c))
                        {
                            JOptionPane.showMessageDialog(null, "UserName is already Taken");
                        }
                        else if("error".equals(c))
                            JOptionPane.showMessageDialog(null, "Error occurred");
                        else if("true".equals(c))
                        {
                            if(pass1.equals(pass2))                //Final password & Email Check
                            {
                               
                                try{
                                    InternetAddress in=new InternetAddress(email);
                                    in.validate();
                                   
                                    String e=this.checkEmail(email);
                        
                                    if("false".equals(e))
                                    {
                                        JOptionPane.showMessageDialog(null, "Email is already Taken");
                                    }
                                    else if("error".equals(e))
                                        JOptionPane.showMessageDialog(null, "Error occurred");
                                    
                                    else if("true".equals(e))
                                    {
                                        boolean s=this.storeData(fn, ln, un, pass1, email, f_path,cla);
                                        if(s==true)                                                        //Final Check
                                        {
                                            Thread t1=new Thread(()->{new SendEmail().registerUserConfirmation(email, un, fn, ln, pass1);});
                                            new User_Login().setVisible(true);
                                            t1.start();
                                            this.dispose();
                                        }
                                        else
                                           JOptionPane.showMessageDialog(null, "Data did not get registered");
                                        }
                                }
                                catch(AddressException ae)
                                {
                                    JOptionPane.showMessageDialog(null, "Email not valid");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Password doesn't match");
                                pass1t.setText("");
                                pass2t.setText("");
                            }
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "User name can only take alphabets and numbers");
                        unt.setText("");
                        pass1t.setText("");
                        pass2t.setText("");
                    }
                }
                else                                    //fn ln condtion check
                {
                    JOptionPane.showMessageDialog(null, "First name and Last name should only consist alohabets");
                    fnt.setText("");
                    lnt.setText("");
                    pass1t.setText("");
                    pass2t.setText("");
                }
            }
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null, "Something went wrong");
        }

        
        //new User_Login().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    public boolean storeData(String fn, String ln, String un, String pass1, String email, String f_path,String cla) 
    {
        String epass=encryptPass.encrypt(pass1);
        try
        {
            Connection con=DBUtil.getConnection();
            PreparedStatement pr=con.prepareStatement("INSERT into user values (null,?,?,?,?,?,?,?)");

            pr.setString(1,fn);
            pr.setString(2,ln);
            pr.setString(3,un);
            pr.setString(4,email);
            pr.setString(5,epass);
            pr.setString(6,f_path);
            pr.setString(7,cla);
            pr.execute();

            return true;
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);           
            return false;
        }
    }
    public String checkUN(String uns)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            PreparedStatement pr=con.prepareStatement("SELECT fname from user WHERE uname='"+uns+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
             
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    public String checkEmail(String email)  
    {
        ResultSet rs=null;
        
        try
        {
            Connection con=DBUtil.getConnection();
            //System.out.println(con.getCatalog()+"hello");
            PreparedStatement pr=con.prepareStatement("SELECT fname from user WHERE email='"+email+"'");
            
            rs=pr.executeQuery();
            //System.out.println("success");
            
            if(rs.next()==false)
            {
                //System.out.print(rs.next());
                return "true";
            }
            return "false";
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            System.out.println(e+"\n");
           System.out.println(e.getMessage());
           return "error";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cla1;
    private javax.swing.JTextField emailt;
    private javax.swing.JTextField f_patht;
    private javax.swing.JTextField fnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel left_panel;
    private javax.swing.JTextField lnt;
    private javax.swing.JPasswordField pass1t;
    private javax.swing.JPasswordField pass2t;
    private javax.swing.JPanel right_panel;
    private javax.swing.JTextField unt;
    // End of variables declaration//GEN-END:variables
}
